// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcNv138xwuX97fc9zymSr-BtsrzLuwrI',
    appId: '1:1098949631969:web:04f4d22257c45ea7dbfca0',
    messagingSenderId: '1098949631969',
    projectId: 'cangijoo-f2f6b',
    authDomain: 'cangijoo-f2f6b.firebaseapp.com',
    storageBucket: 'cangijoo-f2f6b.firebasestorage.app',
    measurementId: 'G-M00STNPD2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD92Tvtu5cXtYGNYFcmYc1D1cFJ-VWJJ_A',
    appId: '1:1098949631969:android:21119cfffb493482dbfca0',
    messagingSenderId: '1098949631969',
    projectId: 'cangijoo-f2f6b',
    storageBucket: 'cangijoo-f2f6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW8yOiRuoG8lRxxLN3kvQm7TfUd9HeTB0',
    appId: '1:1098949631969:ios:39b14d7a8af114e3dbfca0',
    messagingSenderId: '1098949631969',
    projectId: 'cangijoo-f2f6b',
    storageBucket: 'cangijoo-f2f6b.firebasestorage.app',
    androidClientId: '1098949631969-13jenu38ulh52gkkq844l35epsr8q7ao.apps.googleusercontent.com',
    iosClientId: '1098949631969-spi5tj1hroeie9tqhdo8mnla32v0t84t.apps.googleusercontent.com',
    iosBundleId: 'com.cangijoo.cangijoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW8yOiRuoG8lRxxLN3kvQm7TfUd9HeTB0',
    appId: '1:1098949631969:ios:39b14d7a8af114e3dbfca0',
    messagingSenderId: '1098949631969',
    projectId: 'cangijoo-f2f6b',
    storageBucket: 'cangijoo-f2f6b.firebasestorage.app',
    androidClientId: '1098949631969-13jenu38ulh52gkkq844l35epsr8q7ao.apps.googleusercontent.com',
    iosClientId: '1098949631969-spi5tj1hroeie9tqhdo8mnla32v0t84t.apps.googleusercontent.com',
    iosBundleId: 'com.cangijoo.cangijoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcNv138xwuX97fc9zymSr-BtsrzLuwrI',
    appId: '1:1098949631969:web:45aa112eac090dc0dbfca0',
    messagingSenderId: '1098949631969',
    projectId: 'cangijoo-f2f6b',
    authDomain: 'cangijoo-f2f6b.firebaseapp.com',
    storageBucket: 'cangijoo-f2f6b.firebasestorage.app',
    measurementId: 'G-XWDC3GRFH7',
  );

}